UPDATE replay_runs
SET capability = 'BOOK_RECONSTRUCTION_SOURCE_INCOMPLETE'
WHERE capability = 'BOOK_RECONSTRUCTION_UNVERIFIED_FAIL_CLOSED';

ALTER TABLE replay_runs
ALTER COLUMN capability SET DEFAULT 'BOOK_RECONSTRUCTION_SOURCE_INCOMPLETE';
